# Generated by Django 3.2.9 on 2021-12-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infosUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('poids', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sexe', models.CharField(max_length=10)),
                ('objectif', models.CharField(max_length=1000)),
            ],
        ),
    ]
