# Generated by Django 3.2.9 on 2021-12-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setUserInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosutilisateur',
            name='taille',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
