# Generated by Django 3.2.9 on 2021-12-06 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('codePostal', models.CharField(max_length=5)),
                ('logo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.CharField(max_length=300)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uberEatsAPI.restaurant')),
            ],
        ),
    ]
